In [1]:
import numpy as np

## Array searching

> ###  array searching return the index of the value.

In [2]:
arr=np.array([1,2,3,4,5,6,7,3,6,3,3])

In [3]:
x=np.where(arr==3)

In [4]:
print(x)

(array([ 2,  7,  9, 10], dtype=int64),)


> ##### Return the index of value 3

In [5]:
a=np.array(["a","b","c","d"])
c=np.where(a=="b")
c

(array([1], dtype=int64),)

In [6]:
y=np.where(arr%2==0)

In [7]:
print(y)

(array([1, 3, 5, 8], dtype=int64),)


> ##### Return the even numbers

In [8]:
z=np.where(arr%2==1)
# arr%2!=0

In [9]:
print(z)

(array([ 0,  2,  4,  6,  7,  9, 10], dtype=int64),)


> ##### Return odd numbers

## Replacing value

In [10]:
list=np.array([1,2,3,4,5,3,6,7,8,9])
list

array([1, 2, 3, 4, 5, 3, 6, 7, 8, 9])

In [11]:
ten=np.where(list>=5,10,list)
ten

array([ 1,  2,  3,  4, 10,  3, 10, 10, 10, 10])

In [12]:
five=np.where(list==1,12,list)
five

array([12,  2,  3,  4,  5,  3,  6,  7,  8,  9])

## Reshaping array

In [13]:
list

array([1, 2, 3, 4, 5, 3, 6, 7, 8, 9])

### checking the dimension

In [14]:
list.ndim

1

In [15]:
x=np.arange(1,11)

In [16]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
y=x.reshape(2,5)

In [18]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
y.ndim

2

In [20]:
z=np.where(y==3)
z

(array([0], dtype=int64), array([2], dtype=int64))

In [21]:
z1=np.where(y==7)
z1

(array([1], dtype=int64), array([1], dtype=int64))

## Sorting Arrays

In [22]:
x=np.array([0,3,6,2,9,1])
y=np.sort(x)
y

array([0, 1, 2, 3, 6, 9])

In [23]:
descy=-np.sort(-x)
descy

array([9, 6, 3, 2, 1, 0])

In [24]:
d=np.sort(y)[::-1]
d

array([9, 6, 3, 2, 1, 0])

In [25]:
f=np.sort(y)[-1]
f

9

In [26]:
alpha=np.array(["a","z","e","u","b","h"])
order=np.sort(alpha)
order

array(['a', 'b', 'e', 'h', 'u', 'z'], dtype='<U1')

## Searchsorted()

In [27]:
x=np.searchsorted(arr,3)

In [28]:
x

2

In [29]:
y=np.searchsorted(arr,3,side="right")

In [30]:
y

3

In [31]:
arr1=np.array([6,7,8,9])
ss=np.searchsorted(arr1,7)
ss

1

In [32]:
ss1=np.searchsorted(arr1,7,side="right")
ss1

2

In [33]:
arr2=np.array([1,2,3,4])
x=np.searchsorted(arr2,1)
x

0

In [34]:
y=np.searchsorted(arr2,1,side="right")
y

1

In [35]:
s=np.array([1,4,6])
a=np.searchsorted(s,2)
a

1

## Array Filtering

In [36]:
arr=np.array([10,11,12,13,14,15])
x=[True,True,False,True,False,False]
newarr=arr[x]
newarr

array([10, 11, 13])

In [37]:
arr=np.arange(1,15)
filter_arrays=[]
for i in arr:
    if i%2==0:
        filter_arrays.append(True)
    else:
        filter_arrays.append(False)
newarr=arr[filter_arrays]
print(newarr)

[ 2  4  6  8 10 12 14]


In [38]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
filter_arrays

[False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True]

### array filter directly

In [40]:
arr=np.arange(1,15)
filter_array=arr%2!=0
newarr=arr[filter_array]
newarr

array([ 1,  3,  5,  7,  9, 11, 13])

# Random number generating

### random()

#### rand() --> float numbers

In [41]:
rand=np.random.rand(5)
rand

array([0.41223357, 0.16440971, 0.52383041, 0.28072849, 0.25868522])

#### randint() --> integers

In [42]:
rand=np.random.randint(1,5)
rand

1

In [43]:
a=np.random.randint(1,10,5)
a

array([3, 3, 6, 8, 7])

In [44]:
r=np.random.randint(1,5,6)
r

array([3, 4, 1, 2, 2, 2])

## 2D array

In [45]:
a=np.random.rand(4,2)
a

array([[0.79728037, 0.29520277],
       [0.34493505, 0.3812763 ],
       [0.11160366, 0.7557262 ],
       [0.62131704, 0.18534705]])

In [46]:
b=np.random.rand(3,4,6)
b

array([[[0.76586943, 0.58311885, 0.46955794, 0.48453838, 0.57672558,
         0.02957461],
        [0.91362188, 0.99166615, 0.03322847, 0.48565824, 0.62669178,
         0.3337688 ],
        [0.26867421, 0.26397154, 0.45625015, 0.24425519, 0.93147875,
         0.42462233],
        [0.44724387, 0.02285818, 0.34074326, 0.90669357, 0.93129568,
         0.31487251]],

       [[0.76974122, 0.68195789, 0.03632342, 0.3863959 , 0.89566546,
         0.03506193],
        [0.274417  , 0.62775949, 0.35445884, 0.45156587, 0.25200469,
         0.28893012],
        [0.44357966, 0.42606708, 0.13233954, 0.22641027, 0.75526725,
         0.94481671],
        [0.04339679, 0.97546776, 0.81208705, 0.07628792, 0.70834196,
         0.18654497]],

       [[0.32308994, 0.32054244, 0.08327207, 0.51716197, 0.25633792,
         0.95413898],
        [0.86488155, 0.20233422, 0.15673949, 0.88427307, 0.44002346,
         0.73585451],
        [0.80855813, 0.37296112, 0.31906671, 0.61558628, 0.72909712,
         0.368770

In [47]:
c=np.random.rand(4,3,2,5)
c

array([[[[0.09863569, 0.68641511, 0.64730044, 0.13552416, 0.74049714],
         [0.70013847, 0.01282258, 0.61195569, 0.29700481, 0.89433762]],

        [[0.83912458, 0.38455622, 0.18105375, 0.60975299, 0.65927057],
         [0.56376236, 0.63498211, 0.60445745, 0.23589085, 0.38119631]],

        [[0.97056883, 0.81928541, 0.40398383, 0.7554172 , 0.62170608],
         [0.2292695 , 0.21346474, 0.96658336, 0.59510511, 0.30077241]]],


       [[[0.48476606, 0.19995249, 0.92168572, 0.97798063, 0.8300171 ],
         [0.44467793, 0.79112936, 0.48767712, 0.52176964, 0.60480402]],

        [[0.41670564, 0.47649029, 0.10477638, 0.23459754, 0.9321538 ],
         [0.03483293, 0.31617748, 0.65575401, 0.88225971, 0.85960783]],

        [[0.6008065 , 0.41371079, 0.36555031, 0.4524542 , 0.17815914],
         [0.08758517, 0.58947726, 0.76770875, 0.04684728, 0.71738879]]],


       [[[0.9729036 , 0.82990487, 0.18611418, 0.54282294, 0.58932762],
         [0.2720048 , 0.04082901, 0.30406261, 0.03580968, 0.3

In [48]:
a=np.random.randint(10,50,size=(4,5))
a

array([[41, 47, 13, 31, 23],
       [20, 37, 21, 45, 35],
       [43, 29, 12, 45, 38],
       [25, 30, 43, 31, 28]])

In [49]:
rand_uni_arr=np.random.uniform(5,10,10)
rand_uni_arr

array([8.90578648, 9.76357986, 9.17183595, 8.71590709, 7.03442284,
       5.91244053, 9.77737574, 9.21932417, 7.03554078, 5.41938672])

In [50]:
rand_uni_arr=np.random.rand(5,10,10)
rand_uni_arr

array([[[0.40429438, 0.30383186, 0.60745006, 0.71341064, 0.30613011,
         0.46829441, 0.57403367, 0.87127077, 0.72834821, 0.05616076],
        [0.39276926, 0.89487249, 0.01320506, 0.38149544, 0.38987132,
         0.30427879, 0.5754596 , 0.57654047, 0.61720199, 0.93333874],
        [0.10136196, 0.92677535, 0.70829937, 0.62261729, 0.99576824,
         0.13025914, 0.14394157, 0.11950928, 0.77289621, 0.24489465],
        [0.63575769, 0.81231824, 0.90389237, 0.68518012, 0.90015058,
         0.34596868, 0.1370737 , 0.31476821, 0.5549888 , 0.61390802],
        [0.66854138, 0.38393468, 0.37523962, 0.06569895, 0.31373501,
         0.59598229, 0.0228244 , 0.22513727, 0.62498783, 0.56791854],
        [0.4550771 , 0.52816858, 0.25972236, 0.92263378, 0.0995771 ,
         0.83100432, 0.61801574, 0.25191698, 0.24737279, 0.91149284],
        [0.77817611, 0.26250657, 0.81679632, 0.25990875, 0.2276068 ,
         0.00677588, 0.88188947, 0.9447486 , 0.67427033, 0.05454704],
        [0.0710196 , 0.5782

In [52]:
a=np.random.rand(5)
a

array([0.75046226, 0.42626187, 0.87748746, 0.99517519, 0.94487389])

In [53]:
a=np.random.rand(5)
a

array([0.44380487, 0.30203964, 0.65961504, 0.1472334 , 0.07134295])

In [54]:
a=np.random.rand(5)
a

array([0.49471701, 0.60236097, 0.65351539, 0.14236683, 0.1168099 ])

In [55]:
a=np.random.seed(42)
a=np.random.rand(5)
a

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [56]:
a=np.random.seed(42)
a=np.random.rand(5)
a

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [59]:
np.random.seed(35)
b=np.random.randint(3,9,5)
b

array([4, 7, 4, 7, 3])

In [62]:
np.random.seed(76)
b=np.random.randint(3,9,5)
b

array([4, 3, 5, 5, 4])